### PR TITLE
Help flag in Foreach returns usage

### LINKED ISSUE #96: turbolift foreach --help doesn't work
When I run `turbolift foreach --help` I expect to see the help of foreach command. Instead, turbolift runs standalone `--help` on all the repositories in the workspace, which obviously fails.

### PR DESCRIPTION
**Pull request by sledigabel**
Fixes #96.

This PR fixes the current bug in the ForEach command where the help flag
is not parsed properly and doesn't return the usage.

### CODE REVIEW

File: cmd/foreach/foreach.go [hunk 1]
```diff
@@ -30,23 +30,31 @@ import (
...
 
-var repoFile string = "repos.txt"
+var (
+	repoFile string = "repos.txt"
+	helpFlag bool   = false
+)
 
-func parseForeachArgs(args []string) (strippedArgs []string) {
+func parseForeachArgs(args []string) []string {
+	strippedArgs := make([]string, 0)
```
Comment (sledigabel) [inline cmd/foreach/foreach.go:39]: It is safer for `strippedArgs` to be initialised as an empty array rather than leaving the zero value when being returned.

**Review by seraco — COMMENTED** [review]
Maybe we can add a test checking that help is not triggered if it comes after the command?

**Review by seraco — COMMENTED** [review]
Is the usage message correct?

```
        foreach SHELL_COMMAND [flags]
        
        Flags:
          -h, --help           help for foreach
              --repos string   A file containing a list of repositories to clone. (default "repos.txt")
```

Shouldn't it be?

```
        foreach [flags] SHELL_COMMAND
        
        Flags:
          -h, --help           help for foreach
              --repos string   A file containing a list of repositories to clone. (default "repos.txt")
```

**Comment by sledigabel** [comment]
> Maybe we can add a test checking that help is not triggered if it comes after the command?

Good shout. Will add it.

**Comment by sledigabel** [comment]
> Is the usage message correct?
> 
> ```
>         foreach SHELL_COMMAND [flags]
>         
>         Flags:
>           -h, --help           help for foreach
>               --repos string   A file containing a list of repositories to clone. (default "repos.txt")
> ```
> 
> Shouldn't it be?
> 
> ```
>         foreach [flags] SHELL_COMMAND
>         
>         Flags:
>           -h, --help           help for foreach
>               --repos string   A file containing a list of repositories to clone. (default "repos.txt")
> ```

You're 💯 right. Didn't notice it from the previous PR or in my test.
The `[flags]` thing is added by cobra itself, I'm not sure how to change this. I'll read up on it.

**Review by seraco — APPROVED** [review]
Looks great. 🎉

**Comment by sledigabel** [comment]
@seraco thanks for your review 🎉 
FYI, did a bit of digging. This flag [here](https://github.com/Skyscanner/turbolift/pull/98/files#diff-8c216170a244578e56b15b077f91fc8df8444fd179be8e6b1f934ced75e30f79R64) is [disabling the auto addition of the `[flags]` string](https://github.com/spf13/cobra/blob/main/command.go#L1397-L1399).

Then I wondered how the `Use` field was affecting the verb, turns out the name of the command is generated from the first word in the `Use` line: https://github.com/spf13/cobra/blob/main/command.go#L1445-L1452

**Review by Dan7-7-7 — APPROVED** [review]
looks good!

**Comment by rnorth** [comment]
@sledigabel do you want to merge?
